#!/usr/bin/env sh
args="--disable=I,C,R,logging-not-lazy,wildcard-import,unused-wildcard-import,fixme,broad-except,bare-except,eval-used,exec-used,global-statement,logging-format-interpolation,no-name-in-module,import-error"
failed=0
for file in cime_config/buildexe cime_config/buildnml cime_config/runseq/*
do
    pylint $args $file || failed=$(( failed + 1 ))
done
exit $failed
